name: CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        php: [7.1, 7.2, 7.3, 7.4, 8.0]
        mockery: [1.0.*, 1.1.*, 1.2.*, 1.3.*, ^1.4]
        composer_flags: [ --prefer-stable --prefer-lowest, --prefer-stable ]
        exclude:
          - { php: 7.1, mockery: ^1.4, composer_flags: --prefer-stable }
          - { php: 7.1, mockery: ^1.4, composer_flags: --prefer-stable --prefer-lowest }
          - { php: 7.2, mockery: ^1.4, composer_flags: --prefer-stable }
          - { php: 7.2, mockery: ^1.4, composer_flags: --prefer-stable --prefer-lowest }
          - { php: 8.0, mockery: 1.0.*, composer_flags: --prefer-stable }
          - { php: 8.0, mockery: 1.0.*, composer_flags: --prefer-stable --prefer-lowest }
          - { php: 8.0, mockery: 1.1.*, composer_flags: --prefer-stable }
          - { php: 8.0, mockery: 1.1.*, composer_flags: --prefer-stable --prefer-lowest }
          - { php: 8.0, mockery: 1.2.*, composer_flags: --prefer-stable }
          - { php: 8.0, mockery: 1.2.*, composer_flags: --prefer-stable --prefer-lowest }
          - { php: 8.0, mockery: 1.3.*, composer_flags: --prefer-stable --prefer-lowest }
          - { php: 8.0, mockery: ^1.4, composer_flags: --prefer-stable --prefer-lowest }

    steps:
      - uses: actions/checkout@v2

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          coverage: xdebug

      - name: Adjust package versions
        run: |
          composer require "mockery/mockery:${{ matrix.mockery }}" --no-update ${{ matrix.composer_flags }}
          composer require "phpunit/phpunit" --dev --prefer-stable
          composer update ${{ matrix.composer_flags }}

      - run: mkdir -p build/logs
      - run: vendor/bin/phpunit --coverage-clover build/logs/clover.xml

      - name: Upload Coverage
        uses: nick-invision/retry@v2
        env:
          COVERALLS_REPO_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          COVERALLS_PARALLEL: 'true'
          COVERALLS_FLAG_NAME: 'php:${{ matrix.php }}'
        with:
          timeout_minutes: 1
          max_attempts: 3
          command: |
            composer global require php-coveralls/php-coveralls
            php-coveralls --coverage_clover=build/logs/clover.xml -v

  coverage-aggregation:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Aggregate Coverage
        uses: coverallsapp/github-action@master
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          parallel-finished: true
